services:
  postgres:
    image: postgres:16-alpine
    container_name: eagle-bank-db
    environment:
      POSTGRES_USER: eagle
      POSTGRES_PASSWORD: eagle
      POSTGRES_DB: eagle_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
